console.log('----start-----init----')
console.log('进行了一些修改xxx,现在提交到main上')
console.log('-----')
console.log('这里也进行一些小小的修改传递到branch1')
console.log('这里再写一些东西')
console.log('在分支里面再写一些东西.....')
console.log('上面的success')
console.log('这是开始使用git flow 的命令了')
console.log('再写一点点...继续git flow 传递')